language: java
jdk:
  - openjdk11
os:
  - linux
addons:
  sonarcloud:
    organization: "dachiarelli89"
    token: ${SONAR_TOKEN}
script:
  - mvn clean install
  - sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_API_KEY}
  app: vodafone-tax-code-api
